AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_special

Layout/IndentationConsistency:
  EnforcedStyle: indented_internal_methods

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false



Metrics/BlockLength:
  Exclude:
    - '**/spec/**/*'

Metrics/ModuleLength:
  Exclude:
    - '**/spec/**/*'

Metrics/LineLength:
  Max: 120
  IgnoredPatterns:
    - '^\W*\#'



Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
